name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    
jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm ci
        npm i mocha

    - name: Run Tests
      run: |
        npm run test